### ISSUE TITLE
Back pads of the expansion port header footprint have their solder mask cutouts on the wrong layer

### ISSUE THREAD

**Issue by thierer** [bwack/C64-cartridge-template-kicad5#1]
As I learned the hard way :) the back pads of the expansion port footprint have their solder mask cutout on the front layer, so they get covered in solder mask:

![solder mask](https://user-images.githubusercontent.com/240625/120022992-77067b80-bfed-11eb-8691-b283d32d76ef.png)

I have a corrected version at https://github.com/thierer/C64-cartridge-template-kicad5, in case you'd prefer to pull from there instead of fixing it yourself.

**Comment by bwack** [comment]
Hi. Thanks a lot. Sorry to hear you had to find out the hard way. I wonder if it has to do with old and new version of Kicad. I mean, why would that happen on purpose?
 or maybe I just hadn't noticed since I always put a large soldermask restrict block over the whole connector.
Thanks for the fork. I can fix it quickly here.

**Comment by bwack** [comment]
OK I see now how I did that wrong. since I put pads on the front and the back, rather than one footprint on front, and one flipped to the back, i messed up the F.Mask and B.Mask selection :)

**Comment by bwack** [comment]
I added GND fill between pin 2 and 3, and a Mask around the edge connector on top and bottom.

![image](https://user-images.githubusercontent.com/11380333/120873691-73ea2d00-c5a3-11eb-8570-717c8dc5cd96.png)

![image](https://user-images.githubusercontent.com/11380333/120873673-659c1100-c5a3-11eb-8e9f-7c73f51de128.png)

**Comment by thierer** [comment]
No worries, it's for a personal project; I just sanded the solder mask off. My bad that I didn't pay attention.

Thanks for the fix and for making the template available in the first place!
